"""后端自有的 Agent 兼容知识图谱 HTML 渲染器。"""
from __future__ import annotations

import json
from typing import Any


def render_graph_html(nodes: list[dict[str, Any]], edges: list[dict[str, Any]]) -> str:
    """生成带完整 Agent 交互契约的独立 vis.js 图谱页面。"""
    node_data = json.dumps(nodes, ensure_ascii=False, indent=2).replace("</", "<\\/")
    edge_data = json.dumps(edges, ensure_ascii=False, indent=2).replace("</", "<\\/")
    counts = {kind: sum(edge.get("type") == kind for edge in edges) for kind in ("EXTRACTED", "INFERRED", "AMBIGUOUS")}
    html = """<!doctype html><html><head><meta charset="utf-8"><title>LLM Wiki — Knowledge Graph</title>
<script src="https://unpkg.com/vis-network/standalone/umd/vis-network.min.js"></script>
<style>body{margin:0;background:#1a1a2e;color:#eee;font-family:Inter,Arial}#graph{width:100vw;height:100vh}#controls,#stats{position:fixed;background:rgba(10,10,30,.88);border:1px solid #ffffff18;border-radius:10px;z-index:10;padding:14px;backdrop-filter:blur(8px)}#controls{top:10px;left:10px;width:260px}#stats{top:10px;right:10px;font-size:12px}.filter{margin-top:10px;padding-top:8px;border-top:1px solid #ffffff18;font-size:12px}.filter input{accent-color:#ff5722}#search{box-sizing:border-box;width:100%;padding:7px;background:#222;color:#eee;border:1px solid #444;border-radius:6px}#drawer{position:fixed;right:0;top:0;width:clamp(480px,33vw,720px);max-width:100vw;height:100vh;display:none;flex-direction:column;background:#070a18f5;border-left:1px solid #ffffff18;z-index:20}#drawer.open{display:flex}#drawer-head{padding:18px;border-bottom:1px solid #ffffff18}#drawer-title{margin:0;font-size:20px}#close{float:right;background:none;border:0;color:#aaa;font-size:24px;cursor:pointer}#meta,#path,#preview{margin-top:8px;color:#aab;font-size:12px}#preview{font-size:13px;color:#ddd;line-height:1.6}#related{padding:12px 18px;font-size:12px;color:#aaa}.chip{margin:4px;padding:5px 10px;border:1px solid #ffffff18;border-radius:999px;background:#ffffff12;color:#eee;cursor:pointer}#markdown{overflow:auto;padding:0 18px 18px;line-height:1.72}#markdown blockquote,#markdown pre{margin:1em 0;padding:12px;background:#ffffff0a;border-left:3px solid #65b5ff;white-space:pre-wrap}#markdown code{color:#ffde91}.wikilink{color:#86c8ff;font-weight:600}@media(max-width:960px){#drawer{width:100vw}}</style></head><body>
<div id="controls"><h3>LLM Wiki Graph</h3><p><input id="search" placeholder="Search nodes..." oninput="applyFilters()"></p><div><span style="background:#4caf50;padding:3px">source</span> <span style="background:#2196f3;padding:3px">entity</span> <span style="background:#ff9800;padding:3px">concept</span></div><div class="filter">Edge Types<br><label><input id="cb-extracted" type="checkbox" checked> Extracted (@@EXTRACTED@@)</label><br><label><input id="cb-inferred" type="checkbox" checked> Inferred (@@INFERRED@@)</label><br><label><input id="cb-ambiguous" type="checkbox"> Ambiguous (@@AMBIGUOUS@@)</label></div><div class="filter">Min Confidence <input id="conf-slider" type="range" min="0" max="100" value="50" oninput="applyFilters()"> <span id="conf-val">0.50</span></div><p>Click a node to highlight connected neighbors. Click the background to restore the full graph.</p></div>
<div id="stats"></div><div id="graph"></div><aside id="drawer"><div id="drawer-head"><button id="close" onclick="clearSelection()">×</button><h2 id="drawer-title"></h2><div id="meta"></div><div id="path"></div><div id="preview"></div></div><div id="related">Related nodes: <span id="related-list"></span></div><article id="markdown"></article></aside>
<script>
const originalNodes=@@NODES@@,originalEdges=@@EDGES@@.map(e=>Object.assign({id:e.from+"->"+e.to+":"+(e.type||"INFERRED")},e)),nodes=new vis.DataSet(originalNodes),edges=new vis.DataSet(originalEdges),nodeMap=new Map(originalNodes.map(n=>[n.id,n]));let active=null;
function esc(s){return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}function renderMarkdown(s){let out=[],list=null;for(let line of String(s||"").replace(/^---\\n[\s\S]*?\\n---\\n?/,"").split(/\\r?\\n/)){let h=line.match(/^(#{1,6})\s+(.+)/),u=line.match(/^[-*]\s+(.+)/),o=line.match(/^\d+\.\s+(.+)/);if(h){out.push("<h"+h[1].length+">"+inline(h[2])+"</h"+h[1].length+">");list=null}else if(u||o){let kind=u?"ul":"ol";if(list!==kind){out.push("<"+kind+">");list=kind}out.push("<li>"+inline((u||o)[1])+"</li>")}else{if(list){out.push("</"+list+">");list=null}if(/^>\s?/.test(line))out.push("<blockquote>"+inline(line.slice(1))+"</blockquote>");else if(/^(-{3,}|\*{3,})$/.test(line.trim()))out.push("<hr>");else if(line.trim())out.push("<p>"+inline(line)+"</p>")}}if(list)out.push("</"+list+">");return out.join("")}function inline(s){return esc(s).replace(/\[\[([^\]]+)\]\]/g,'<span class="wikilink">[[$1]]</span>').replace(/\x60([^\x60]+)\x60/g,"<code>$1</code>").replace(/\*\*([^*]+)\*\*/g,"<b>$1</b>")}
function state(){let v=Number(document.getElementById("conf-slider").value)/100;document.getElementById("conf-val").textContent=v.toFixed(2);return {v,types:new Set(["EXTRACTED","INFERRED","AMBIGUOUS"].filter(x=>document.getElementById("cb-"+x.toLowerCase()).checked))}}function applyFilters(){let q=document.getElementById("search").value.toLowerCase(),s=state(),shown=originalEdges.filter(e=>s.types.has(e.type)&&Number(e.confidence??1)>=s.v),neighbors=new Map();shown.forEach(e=>{[e.from,e.to].forEach((x,i,a)=>{if(!neighbors.has(x))neighbors.set(x,new Set());neighbors.get(x).add(a[1-i])})});let related=active?new Set([active,...(neighbors.get(active)||[])]):null,visible=0;nodes.update(originalNodes.map(n=>{let hidden=!active&&!q&&!neighbors.has(n.id),strong=(!q||n.label.toLowerCase().includes(q))&&(!related||related.has(n.id));if(!hidden)visible++;return {id:n.id,hidden,color:{background:strong?n.color:"rgba(255,255,255,.14)",border:strong?n.color:"rgba(255,255,255,.22)"},font:{color:strong?"#eee":"#ffffff33"},borderWidth:n.id===active?5:2,size:n.id===active?18:12}}));edges.update(originalEdges.map(e=>({id:e.id,hidden:!shown.includes(e),width:active&&(e.from===active||e.to===active)?2.8:1,color:related&&(related.has(e.from)||related.has(e.to))?e.color:"#ffffff22"})));document.getElementById("stats").textContent=visible+" nodes · "+shown.length+" edges";if(active)openDrawer(nodeMap.get(active),related)}function openDrawer(n,related){document.getElementById("drawer").classList.add("open");document.getElementById("drawer-title").textContent=n.label;document.getElementById("meta").textContent=n.type+" · community "+n.group;document.getElementById("path").textContent=n.path;document.getElementById("preview").textContent=n.preview||"";document.getElementById("markdown").innerHTML=renderMarkdown(n.markdown);let root=document.getElementById("related-list");root.innerHTML="";originalNodes.filter(x=>related.has(x.id)&&x.id!==n.id).sort((a,b)=>a.label.localeCompare(b.label)).forEach(x=>{let b=document.createElement("button");b.className="chip";b.textContent=x.label;b.onclick=()=>focusNode(x.id);root.appendChild(b)})}function focusNode(id){active=id;applyFilters();network.focus(id,{scale:1.1,animation:{duration:300,easingFunction:"easeInOutQuad"}})}function clearSelection(){active=null;document.getElementById("drawer").classList.remove("open");applyFilters()}
const count=originalNodes.length,network=new vis.Network(document.getElementById("graph"),{nodes,edges},{nodes:{shape:"dot",font:{color:"#ddd",size:12,strokeWidth:3,strokeColor:"#111"},scaling:{min:8,max:40,label:{enabled:true,min:10,max:20,drawThreshold:6,maxVisible:24}}},edges:{width:.8,smooth:{type:"continuous"},arrows:{to:{enabled:true,scaleFactor:.4}},color:{inherit:false}},physics:{stabilization:{iterations:250,updateInterval:25,fit:true},barnesHut:{gravitationalConstant:count>80?-8000:count>30?-5000:-2000,springLength:count>80?250:count>30?200:150,springConstant:.02,damping:.15}},interaction:{hover:true,tooltipDelay:150,hideEdgesOnDrag:true,hideEdgesOnZoom:true}});network.once("stabilizationIterationsDone",()=>network.fit({animation:{duration:400,easingFunction:"easeInOutQuad"}}));network.on("click",p=>p.nodes.length?focusNode(p.nodes[0]):clearSelection());applyFilters();
</script></body></html>"""
    return (
        html.replace("@@NODES@@", node_data)
        .replace("@@EDGES@@", edge_data)
        .replace("@@EXTRACTED@@", str(counts["EXTRACTED"]))
        .replace("@@INFERRED@@", str(counts["INFERRED"]))
        .replace("@@AMBIGUOUS@@", str(counts["AMBIGUOUS"]))
    )
